# Generated by Django 3.2.7 on 2021-10-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
