# Generated by Django 4.0.3 on 2022-03-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
