# Generated by Django 3.2.7 on 2021-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(max_length=100)),
            ],
        ),
    ]
