# Generated by Django 3.2.7 on 2021-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
