# Generated by Django 3.2.7 on 2021-09-30 06:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_department_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
