# Generated by Django 4.0.3 on 2022-03-10 13:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_department_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
